comment:
  layout: 'reach, diff, files'

ignore:
- 'examples/'

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 80%
    patch:
      default:
        enabled: no # disable patch since it is noisy and not correct
